 <h1>Join the Explorers!</h1>
    <p>Welcome to our community! As a part of the Explorers you'll 
receive our monthly newsletter, weekly specials, and an opportunity to 
write articles for the <a href="http://www.explorecalifornia.org/blog">Explorer's Journal</a> (our blog) and share trip photos in our<a href="http://explorecalifornia.org/explorers/gallery.htm"> photo gallery</a>!</p>
    <p>After you sign up, we'll send out a membership kit. It contains 
two free upgrade vouchers for your next tour and our super-secret 
decoder ring. Use the decoder ring when you go on a two day or more 
Explore California tour to unlock fantastic upgrades and optional tour 
excursions. Hey, being a part of the community has its benefits. Worried
 about privacy? Don't be, we never share your information with anyone. 
Read our <a href="http://explorecalifornia.org/resources/privacy.htm">privacy</a> policy.</p>
    
<?php
  $this->form->setAction($this->url());
  echo $this->form;  
?>